const initState = {
    products: [{
            id: 1,
            name: "Mens shirt",
            image: "shirt.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 2,
            name: "Formal shirt",
            image: "shirt1.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 3,
            name: "dhjkdhkdfk",
            image: "shirt.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 4,
            name: "Blue shirt",
            image: "shirt2.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 5,
            name: "white shirt",
            image: "shirt4.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 6,
            name: "Part ware suit",
            image: "suit.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 7,
            name: "white dress for wedding",
            image: "white_dress.jpeg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 8,
            name: "Long bluedress",
            image: "blue_dress.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 9,
            name: "Long length suit for Lady",
            image: "suit.jpg",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 10,
            name: "dhjkdhkdfk",
            image: "logo.png",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
        {
            id: 11,
            name: "dhjkdhkdfk",
            image: "logo.png",
            price: 20,
            discount: 2,
            discountPrice: 20 - (2 / 100) * 20,
            quantity: 1,
            desc: "jgjhgjhgjhgjhgjh",
        },
    ],
};

const ProductsReducer = (state = initState, action) => {
    switch (action.type) {
        default: return state;
    }
};

export default ProductsReducer;